version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zk-storage-data:/var/lib/zookeeper/data
      - zk-storage-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:29094,EXTERNAL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29094,EXTERNAL://localhost:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_NUM_NETWORK_THREADS: 4
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 512000
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 512000
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 209715200
    volumes:
      - kafka-storage:/var/lib/kafka/data
    depends_on:
      - zookeeper

  akhq:
    image: tchiotludo/akhq:latest
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "kafka:29094"
    depends_on:
      - kafka

  kafka-perf-test-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9094
      - SERVICE_NAME=kafka-perf-test

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-provisioning-datasources:/etc/grafana/datasources

volumes:
  zk-storage-data:
  zk-storage-log:
  kafka-storage:
  prometheus-data:
  grafana-data:
  grafana-provisioning-datasources:
